INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Rio Branco', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Maceió', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Macapá', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Manaus', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Salvador', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Fortaleza', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Brasília*', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Vitória', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Goiânia', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'São Luís', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Cuiabá', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Campo Grande', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Belo Horizonte', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Belém', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'João Pessoa', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Curitiba', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Recife', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Teresina', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Rio de Janeiro', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Natal', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Porto Alegre', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Porto Velho', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Boa Vista', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Florianópolis', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'São Paulo', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Aracaju', NULL, NULL);
INSERT `counties` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Palmas', NULL, NULL);
